FROM datadrivendiscovery/images:ubuntu-xenial-python36

ENV GOPATH=/usr/local/go
ENV PATH="${GOPATH}/bin:${PATH}"

RUN \
 pip3 install pycodestyle==2.3.1 git+https://github.com/mitar/py-backwards.git && \
 pip3 install git+https://github.com/python/mypy.git@2bd11f60f0a0332b4c9537983a6ac7da4416e9ca && \
 pip3 install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl && \
 pip3 install numpy scikit-learn[alldeps] pymc3 torchvision && \
 pip3 install grpcio grpcio-tools

# Go
RUN apt-get update -q -q && \
 apt-get install --yes --force-yes golang-go git curl unzip wget && \
 go get -u github.com/golang/protobuf/proto && \
 go get -u github.com/golang/protobuf/protoc-gen-go && \
 go get -u google.golang.org/grpc && \
 go get github.com/ckaznocha/protoc-gen-lint && \
 curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip && \
 unzip protoc-3.3.0-linux-x86_64.zip -d protoc3 && \
 mv protoc3/bin/protoc /usr/bin/protoc

# JavaScript
RUN wget -O - https://nodejs.org/dist/v6.11.2/node-v6.11.2-linux-x64.tar.xz | tar Jx --strip=1 -C /usr/local --anchored --exclude=node-v6.11.2-linux-x64/CHANGELOG.md --exclude=node-v6.11.2-linux-x64/LICENSE --exclude=node-v6.11.2-linux-x64/README.md && \
 npm install grpc && \
 npm install google-protobuf
